# Generated by Django 5.2.1 on 2025-05-27 05:40

import django.db.models.deletion
import utils.keygen
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0007_alter_nickname_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=utils.keygen.KeyGen.timestamped_alphanumeric_id, max_length=50, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='posts.polloption')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=utils.keygen.KeyGen.timestamped_alphanumeric_id, max_length=50, unique=True)),
                ('has_poll', models.BooleanField(default=False)),
                ('has_event', models.BooleanField(default=False)),
                ('has_image', models.BooleanField(default=False)),
                ('privacy', models.CharField(choices=[('Public', 'Public'), ('Followers', 'Followers'), ('Only me', 'Only me')], default='Public', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_metadata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=utils.keygen.KeyGen.timestamped_alphanumeric_id, max_length=50, unique=True)),
                ('date_time', models.DateTimeField()),
                ('post_code', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='profiles.city')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='posts.postmetadata')),
            ],
        ),
        migrations.CreateModel(
            name='PostPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=utils.keygen.KeyGen.timestamped_alphanumeric_id, max_length=50, unique=True)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='posts.postmetadata')),
            ],
        ),
        migrations.AddField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='posts.postpoll'),
        ),
        migrations.CreateModel(
            name='PostText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=utils.keygen.KeyGen.timestamped_alphanumeric_id, max_length=50, unique=True)),
                ('content', models.TextField(default='')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='posts.postmetadata')),
            ],
        ),
    ]
