# Generated by Django 5.2.1 on 2025-05-27 06:01

import utils.keygen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpoll',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='uid',
            field=models.CharField(default=utils.keygen.KeyGen.timestamped_alphanumeric_id, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='uid',
            field=models.CharField(default=utils.keygen.KeyGen.timestamped_alphanumeric_id, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='postmetadata',
            name='uid',
            field=models.CharField(default=utils.keygen.KeyGen.timestamped_alphanumeric_id, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='postpoll',
            name='uid',
            field=models.CharField(default=utils.keygen.KeyGen.timestamped_alphanumeric_id, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='posttext',
            name='uid',
            field=models.CharField(default=utils.keygen.KeyGen.timestamped_alphanumeric_id, max_length=50, unique=True),
        ),
    ]
