# Generated by Django 5.2.1 on 2025-05-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nickname',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
